### Create a new post
POST http://localhost:3001/post/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU

{
	"content": "Nur Islom create new Post-3"
}

### Get all posts
GET http://localhost:3001/post/all?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU

### Get User posts
GET http://localhost:3001/post/private?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU


### Search post
POST http://localhost:3001/post/search?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU

{
	"keyword": "Nur Islom create new Post-2"
}

### Get list
POST http://localhost:3001/post/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU

{
	"list": [
		1,
		2,
		3,
		4,
		100
	]
}

### Seach list
POST http://localhost:3001/post/search_list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc5MDQ1MjUxMzRfODZiODYzOGEtNTYxNS00NDkzLTk1MWMtOGFiZmFhMDYyZTUyIiwidXNlcl9pZCI6OSwiaWF0IjoxNzA3OTA0NTI1LCJleHAiOjE3Mzk0NDA1MjV9.SsR9SkYdmZJLMYiCeSOxg8QXZ3PObgA42-hUAzR2vNU

{
	"keyword": "Updated",
	"list": [
		1,
		2,
		3,
		4
	]
}

### Get post by id
GET http://localhost:3001/post/find/30
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

### Update post by id
PUT http://localhost:3001/post/update/30
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

{
	"content": "Updated post content."
}



### Delete post by id
DELETE http://localhost:3001/post/delete/30
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

### Create a new AWS post
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

{
	"content": "This is a new post content created by test."
}

### Get all AWS posts
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/all?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

### Search AWS post
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/search?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

{
	"keyword": "is a"
}

### Get AWS post by id
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/find/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

### Update AWS post by id
PUT https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/update/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

{
	"content": "Updated post content. This is a new post content created by test."
}

### Delete AWS post by id
DELETE https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/delete/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

### Get AWS User posts
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/private?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTY5NzkwMzNfYmE4MDEwMDEtNTJkMC00MjBhLWEzZTMtMTIyNDEzNGZiNmI0IiwidXNlcl9pZCI6MSwiaWF0IjoxNzA3ODk2OTc5LCJleHAiOjE3Mzk0MzI5Nzl9.nE3_uWV8y0YNGNaPETIjn8X7-GRoO5lc-tLmOxzMVHU

