### Create a new post
POST http://localhost:3001/post/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"content": "Nurudeen created a new post"
}

### Get all posts
GET http://localhost:3001/post/all?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Get User posts
GET http://localhost:3001/post/private?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA


### Search post
POST http://localhost:3001/post/search?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"keyword": "Nurudeen"
}

### Get list
POST http://localhost:3001/post/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"list": [
		1,
		2,
		3,
		4,
		100
	]
}

### Seach list
POST http://localhost:3001/post/search_list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"keyword": "Updated",
	"list": [
		1,
		2,
		3,
		4
	]
}

### Get post by id
GET http://localhost:3001/post/find/62
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Update post by id
PUT http://localhost:3001/post/update/62
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"content": "Nurudeen updated post content."
}



### Delete post by id
DELETE http://localhost:3001/post/delete/30
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Create a new AWS post
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"content": "This is a new post content created by test."
}

### Get all AWS posts
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/all?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Search AWS post
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/search?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"keyword": "is a"
}

### Get AWS post by id
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/find/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Update AWS post by id
PUT https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/update/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

{
	"content": "Updated post content. This is a new post content created by test."
}

### Delete AWS post by id
DELETE https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/delete/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

### Get AWS User posts
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/post/private?currentLoad=1&limit=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDc4OTkwNTczOTVfMDgyYWZjYWUtOGIxMC00ZGEyLTk2NDEtYWY1OWJmNzNhMmUxIiwidXNlcl9pZCI6NCwiaWF0IjoxNzA3ODk5MDU3LCJleHAiOjE3Mzk0MzUwNTd9.hKjHfjFdFZerprcek4hqQdQkCzRUdmCq9qAoaW7U-NA

