### Create a new reaction
POST http://localhost:3000/reaction/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

{
  "post_id": 5
}

### Get reaction by id
GET http://localhost:3000/reaction/find
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

### Get all reaction by id
GET http://localhost:3000/reaction/all/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

### Update reaction by id
PUT http://localhost:3000/reaction/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

{
  "reaction_type": 2,
  "post_id": 5
}

### Delete reaction by id
DELETE http://localhost:3000/reaction/delete/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

{
  "id": 3
}

### Get all AWS reaction by id
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/reaction/all/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDU4OTg1MzM0NTRfMmVkOWJkODMtNzM4Mi00ZDUyLWEwNjYtOWU3NjE1MWRhMTVkIiwidXNlcl9pZCI6MTgsImlhdCI6MTcwNTg5ODUzNH0.CygPJK8Zf_CA-ke2_Va1vv8S_f95T3T5Q_kYPL1d9Q4

### Create a new AWS reaction
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/reaction/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDYxMjY3NTcwNzdfMjgxYTNhY2EtNGRiMC00NDc5LTlhMWEtY2VhYTFjZjcyZDMzIiwidXNlcl9pZCI6MjIsImlhdCI6MTcwNjEyNjc1OCwiZXhwIjoxNzM3NjYyNzU4fQ.DwApLQfnps9RqK_G1frKswrjiv227Pz0vHlHogi5h90

{
  "post_id": 9
}

### Get AWS reaction by id
GET https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/reaction/find
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDYxMjY3NTcwNzdfMjgxYTNhY2EtNGRiMC00NDc5LTlhMWEtY2VhYTFjZjcyZDMzIiwidXNlcl9pZCI6MjIsImlhdCI6MTcwNjEyNjc1OCwiZXhwIjoxNzM3NjYyNzU4fQ.DwApLQfnps9RqK_G1frKswrjiv227Pz0vHlHogi5h90

### Update AWS reaction by id
PUT https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/reaction/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDYxMjY3NTcwNzdfMjgxYTNhY2EtNGRiMC00NDc5LTlhMWEtY2VhYTFjZjcyZDMzIiwidXNlcl9pZCI6MjIsImlhdCI6MTcwNjEyNjc1OCwiZXhwIjoxNzM3NjYyNzU4fQ.DwApLQfnps9RqK_G1frKswrjiv227Pz0vHlHogi5h90

{
  "reaction_type": 3,
  "post_id": 9
}

### Delete AWS reaction by id
DELETE https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/reaction/delete/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE3MDYxMjY3NTcwNzdfMjgxYTNhY2EtNGRiMC00NDc5LTlhMWEtY2VhYTFjZjcyZDMzIiwidXNlcl9pZCI6MjIsImlhdCI6MTcwNjEyNjc1OCwiZXhwIjoxNzM3NjYyNzU4fQ.DwApLQfnps9RqK_G1frKswrjiv227Pz0vHlHogi5h90

{
  "id": 8
}

