### Create a new comment
POST http://localhost:3000/comment/create/
Content-Type: application/json

{
  "sentence": "This is a comment",
  "post_id": 1,
  "user_id": 11
}

### Get all topic comment
GET http://localhost:3000/comment/all/:id
Content-Type: application/json

{
  "id": 6
}

### Update comment by id
PUT http://localhost:3000/comment/update/:id
Content-Type: application/json

{
  "id": 6,
  "sentence": "No, sorry, for troubling",
  "updated_at": "2024-01-14T14:33:13.000Z"
}

### Delete comment by id
DELETE http://localhost:3000/comment/delete/:id
Content-Type: application/json

{
}
