### Create a new user
POST http://localhost:3000/user/create
Content-Type: application/json

### Update a username
PUT http://localhost:3000/user/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDU4MTgwMzZ9.5otx7tDfybFofMnDhqtA2wwmiSch1DE3vGm3INKpcgc

{
  "id": 16,
  "username": "Yasuke"
}

### Create a new user
POST https://cgfop8siv2.execute-api.ap-northeast-1.amazonaws.com/api/user/create/
